name: Build Production CI

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            dist
          key: aikon-production-cache

      - run: npm ci
      - run: npm run build --if-present
      - run: echo 'dont forget to run npm test'
  stage:
    needs: build
    runs-on: ubuntu-latest
    env:
      STAGE_NAME: production
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - run: rm -Rf * && rm -Rf .github

      - name: Cache Build
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: dist
          key: aikon-production-cache

      - run: mv ./dist/* ./ && rmdir dist
      - run: git config --global user.email "github@aikon.one"
      - run: git config --global user.name "${{ env.STAGE_NAME }}"
      - run: git add .
      - run: git commit -m 'new deployment'
      - run: git push
