name: Build Stage CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            build
          key: ${{ runner.os }}-build-aikon-stage-cache
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm ci
      - run: npm run build --if-present
      - run: echo 'dont forget to run npm test'
  stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Build
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-aikon-stage-cache
      - run: rm .gitignore
      - run: git config --global user.email "stage@aikon.one"
      - run: git config --global user.name "stage"
      - run: git checkout -B stage
      - run: git add .
      - run: git commit -m 'new stage'
      - run: git push -u origin stage
